### ISSUE TITLE
image loader hasn't worked yet.

### ISSUE THREAD

**Issue by teaolivia** [teaolivia/viralin-client#3]
please take a look at .html files that the image loader needed to be solved. here is the error message:

`URIError: Failed to decode param '/%3C%=require('./src/Image/phone_3.png')%%3E'
    at decodeURIComponent (<anonymous>)
    at decode_param (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/index.js:574:18)
    at next (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/index.js:317:13)
    at /Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/index.js:335:12)
URIError: Failed to decode param '/%3C%=require('./src/Image/phone_3.png')%%3E'
    at decodeURIComponent (<anonymous>)
    at decode_param (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/index.js:574:18)
    at next (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/index.js:317:13)
    at /Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/index.js:335:12)`

**Comment by teaolivia** [comment]
`URIError: Failed to decode param '/%3C%=require('./src/Image/phone_3.png')%%3E'
    at decodeURIComponent (<anonymous>)
    at decode_param (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/index.js:574:18)
    at next (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/index.js:317:13)
    at /Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/index.js:335:12)
URIError: Failed to decode param '/%3C%=require('./src/Image/phone_3.png')%%3E'
    at decodeURIComponent (<anonymous>)
    at decode_param (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/index.js:574:18)
    at next (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/index.js:317:13)
    at /Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/theaolivia/projects/viralin/viralin/node_modules/express/lib/router/index.js:335:12)`

**Comment by teaolivia** [comment]
HINT:

make the html inside the public only one to just load the entry .js file, and move the design components of html to render javascript.

**Comment by mahdiarn** [comment]
done, load directly into src/image using import
